apiVersion: v1
entries:
  csi-driver-nfs:
  - apiVersion: v1
    appVersion: v4.5.0
    created: "2023-11-09T08:10:55.052110073Z"
    description: CSI NFS Driver for Kubernetes
    digest: fac216556edb8a983fc3d4c77e6edc45ee13cb7fce2b215af5601cae55e60832
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/latest/csi-driver-nfs-v4.5.0.tgz
    version: v4.5.0
  - apiVersion: v1
    appVersion: v4.5.0
    created: "2023-11-09T08:10:55.059923408Z"
    description: CSI NFS Driver for Kubernetes
    digest: 662f6db409ac14747c72a9fb2955dedc9ade46497704cab3dd0c472f7d56d58f
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.5.0/csi-driver-nfs-v4.5.0.tgz
    version: v4.5.0
  - apiVersion: v1
    appVersion: v4.4.0
    created: "2023-11-09T08:10:55.059133498Z"
    description: CSI NFS Driver for Kubernetes
    digest: 7fba8cbfc47036a0fddadad00ee291c625e359fe1483ef37b57fd09d157c80dd
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.4.0/csi-driver-nfs-v4.4.0.tgz
    version: v4.4.0
  - apiVersion: v1
    appVersion: v4.3.0
    created: "2023-11-09T08:10:55.058239807Z"
    description: CSI NFS Driver for Kubernetes
    digest: 1aef5dec52a6c433dbed2e361bed0ab1fdd6792f845eccb99b7dc7f193c2a71e
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.3.0/csi-driver-nfs-v4.3.0.tgz
    version: v4.3.0
  - apiVersion: v1
    appVersion: v4.2.0
    created: "2023-11-09T08:10:55.057302442Z"
    description: CSI NFS Driver for Kubernetes
    digest: e702f6c9be35f2649f5736ca5fcdc40ab1c6a235f41e7fb2472d208e8a5ebf47
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.2.0/csi-driver-nfs-v4.2.0.tgz
    version: v4.2.0
  - apiVersion: v1
    appVersion: v4.1.0
    created: "2023-11-09T08:10:55.05667503Z"
    description: CSI NFS Driver for Kubernetes
    digest: b2baa2f129976cf2981c8873290aac509aa3c5937ffc319fbf69fbe3271c23eb
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.1.0/csi-driver-nfs-v4.1.0.tgz
    version: v4.1.0
  - apiVersion: v1
    appVersion: v4.0.0
    created: "2023-11-09T08:10:55.055968854Z"
    description: CSI NFS Driver for Kubernetes
    digest: 3145fd12225a639908b14675c8ae1f272bc0e57ffa2895b6f17411486a24229d
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.0.0/csi-driver-nfs-v4.0.0.tgz
    version: v4.0.0
  - apiVersion: v1
    appVersion: v3.1.0
    created: "2023-11-09T08:10:55.054362464Z"
    description: CSI NFS Driver for Kubernetes
    digest: 7e51bb9188b013195cafc265102fa365de9ec5513780e1dfc5363289f811a4d9
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v3.1.0/csi-driver-nfs-v3.1.0.tgz
    version: v3.1.0
  - apiVersion: v1
    appVersion: v3.0.0
    created: "2023-11-09T08:10:55.053638322Z"
    description: CSI NFS Driver for Kubernetes
    digest: 44406231cd5cdada1c62a0541b93b4f5d5a70ccc8c50b33553a8692fe6cfae96
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v3.0.0/csi-driver-nfs-v3.0.0.tgz
    version: v3.0.0
  - apiVersion: v1
    appVersion: v2.0.0
    created: "2023-11-09T08:10:55.052860929Z"
    description: CSI NFS Driver for Kubernetes
    digest: 1a32c6fc016526fe19a0c9e0dfbe83d0ddde67ced533bb5f5d24d713f706c613
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v2.0.0/csi-driver-nfs-v2.0.0.tgz
    version: v2.0.0
generated: "2023-11-09T08:10:55.050813154Z"
